import { writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { diagnoseFailure, formatFailureComment } from '../failure-diagnostic.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const FIXTURES = resolve(HERE, 'fixtures')

describe('diagnoseFailure', () => {
  it('classifies autocompact thrash via the assistant text marker', () => {
    const d = diagnoseFailure(resolve(FIXTURES, 'transcript-autocompact.jsonl'))
    expect(d.isError).toBe(true)
    expect(d.category).toBe('autocompact-thrashed')
    expect(d.numTurns).toBe(15)
    expect(d.durationSec).toBe(1225)
    expect(d.lastAssistantText).toContain('Autocompact is thrashing')
  })

  it('reports success transcripts as non-error', () => {
    const d = diagnoseFailure(resolve(FIXTURES, 'transcript-success.jsonl'))
    expect(d.isError).toBe(false)
    expect(d.category).toBe('exited-mid-task')
    expect(d.numTurns).toBe(12)
  })

  it('classifies "exited before any tool call" when no tool_use events present', () => {
    const d = diagnoseFailure(resolve(FIXTURES, 'transcript-no-tool-calls.jsonl'))
    expect(d.category).toBe('exited-before-any-tool-call')
    expect(d.numTurns).toBe(1)
  })

  it('classifies truncated transcripts (no result event) distinctly', () => {
    const d = diagnoseFailure(resolve(FIXTURES, 'transcript-truncated.jsonl'))
    expect(d.category).toBe('transcript-truncated-no-result-event')
    expect(d.isError).toBe(true)
    expect(d.numTurns).toBeNull()
  })

  it('handles missing transcript file gracefully', () => {
    const d = diagnoseFailure('/nonexistent/path.jsonl')
    expect(d.category).toBe('transcript-unreadable')
    expect(d.isError).toBe(true)
  })

  it('handles empty transcript file', () => {
    const empty = resolve(tmpdir(), `empty-${Date.now()}.jsonl`)
    writeFileSync(empty, '')
    const d = diagnoseFailure(empty)
    expect(d.category).toBe('transcript-empty')
  })
})

describe('formatFailureComment', () => {
  it('includes AI disclaimer prefix and outcome tag', () => {
    const comment = formatFailureComment({
      diagnostic: diagnoseFailure(resolve(FIXTURES, 'transcript-autocompact.jsonl')),
      workflowRunUrl: 'https://github.com/foo/bar/actions/runs/12345',
      runId: '12345',
    })
    expect(comment).toMatch(/^>\s+\*This was generated by AI during triage\.\*/m)
    expect(comment).toContain('<!-- fix-bot: run=12345 status=failed category=autocompact-thrashed -->')
  })

  it("embeds Claude's last message as a quote block when available", () => {
    const comment = formatFailureComment({
      diagnostic: diagnoseFailure(resolve(FIXTURES, 'transcript-autocompact.jsonl')),
      workflowRunUrl: 'https://example.com/run/1',
      runId: '1',
    })
    expect(comment).toContain('Last message from Claude')
    expect(comment).toContain('Autocompact is thrashing')
  })

  it('includes workflow run URL for maintainer to investigate', () => {
    const comment = formatFailureComment({
      diagnostic: diagnoseFailure(resolve(FIXTURES, 'transcript-autocompact.jsonl')),
      workflowRunUrl: 'https://github.com/gazetta-studio/gazetta-studio/actions/runs/99999',
      runId: '99999',
    })
    expect(comment).toContain('https://github.com/gazetta-studio/gazetta-studio/actions/runs/99999')
  })
})
