/**
 * prior-reviewer-note tests — failing-test commit per rule 31 TDD-first ordering.
 *
 * Covers the gap feature-bot has today: a cut's `priorReviewerNote` is
 * scoped to a single generator-critic run, so when the maintainer
 * removes `ready-for-human` to requeue a cut, the next run starts
 * blind — repeating the mistake that got it rejected. The helper
 * recovers Agent B's last note from the escalation comment the previous
 * run posted, keyed by a `source=reviewer` tag we add to the outcome
 * marker.
 *
 * The helper is pure; the orchestrator wiring is grepped from
 * `index.ts` + `route-attempt.ts` + `prompts/per-cut.md` the same way
 * `refinement-handoff.test.ts` grep-pins its hand-off invariants, so
 * the tests cover both the parser and the format contract it depends on.
 */
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { escalationOutcomeTag, extractPriorReviewerNote } from '../prior-reviewer-note.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const INDEX_SRC = readFileSync(resolve(HERE, '..', 'index.ts'), 'utf-8')
const ROUTE_ATTEMPT_SRC = readFileSync(resolve(HERE, '..', 'route-attempt.ts'), 'utf-8')
const PROMPT_SRC = readFileSync(resolve(HERE, '..', 'prompts/per-cut.md'), 'utf-8')

/**
 * Build a feature-bot escalation comment in the format `escalateToHuman`
 * now emits. Shared between tests + an invariant assertion that the
 * production code uses the same shape via `escalationOutcomeTag`.
 */
function buildEscalationComment(opts: {
  issueNumber: number
  reason: string
  source: 'reviewer' | 'orchestrator'
  note: string
  runId?: string
}): string {
  const runId = opts.runId ?? '123'
  const quotedNote = opts.note.replace(/\n/g, '\n> ')
  const tag = escalationOutcomeTag({
    issueNumber: opts.issueNumber,
    reason: opts.reason,
    runId,
    source: opts.source,
  })
  return `> *This was generated by AI during triage.*

⚠ **Feature-bot escalation — needs human attention.**

**Reason:** \`${opts.reason}\`

**Note from the loop:**

> ${quotedNote}

**Workflow run:** (local)

${tag}`
}

describe('escalationOutcomeTag', () => {
  it('builds a feature-bot escalation outcome tag with source=', () => {
    const tag = escalationOutcomeTag({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      runId: '42',
      source: 'reviewer',
    })
    expect(tag).toContain('feature-bot: escalation issue=517')
    expect(tag).toContain('reason=wrong-root-cause')
    expect(tag).toContain('run=42')
    expect(tag).toContain('source=reviewer')
    expect(tag.startsWith('<!--')).toBe(true)
    expect(tag.endsWith('-->')).toBe(true)
  })

  it('round-trips through extractPriorReviewerNote', () => {
    const body = buildEscalationComment({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'use the singular `{kind}` path',
    })
    expect(extractPriorReviewerNote([body], 517)).toBe('use the singular `{kind}` path')
  })
})

describe('extractPriorReviewerNote', () => {
  it('returns null for an empty comment list', () => {
    expect(extractPriorReviewerNote([], 517)).toBeNull()
  })

  it('returns null when no comments carry a feature-bot escalation tag', () => {
    expect(extractPriorReviewerNote(['random', 'another unrelated comment'], 517)).toBeNull()
  })

  it('extracts the quoted note from a source=reviewer escalation', () => {
    const body = buildEscalationComment({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'use the singular `{kind}` path, not plural',
    })
    expect(extractPriorReviewerNote([body], 517)).toBe('use the singular `{kind}` path, not plural')
  })

  it('ignores source=orchestrator escalations', () => {
    // Per Q — budget / crash / dep notes are orchestrator-generated and
    // would mislead Agent A if seeded as reviewer feedback.
    const body = buildEscalationComment({
      issueNumber: 517,
      reason: 'needs-human',
      source: 'orchestrator',
      note: 'Cut exceeded the per-cut time budget (120 min)',
    })
    expect(extractPriorReviewerNote([body], 517)).toBeNull()
  })

  it('ignores legacy (untagged, pre-source=) escalation comments', () => {
    // Without a source= tag we cannot tell whether the note is Agent B's
    // verdict text or orchestrator metadata. Legacy comments are ignored
    // — missing a reviewer note is strictly safer than misclassifying
    // orchestrator text as reviewer feedback.
    const body = `> *This was generated by AI during triage.*

⚠ **Feature-bot escalation — needs human attention.**

**Reason:** \`wrong-root-cause\`

**Note from the loop:**

> old untagged note

<!-- feature-bot: escalation issue=517 reason=wrong-root-cause run=1 -->`
    expect(extractPriorReviewerNote([body], 517)).toBeNull()
  })

  it('returns the LATEST source=reviewer note when multiple exist', () => {
    const older = buildEscalationComment({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'older reviewer note',
      runId: '100',
    })
    const newer = buildEscalationComment({
      issueNumber: 517,
      reason: 'refinement-exhausted',
      source: 'reviewer',
      note: 'newer reviewer note',
      runId: '200',
    })
    // Comments are listed chronologically (oldest first).
    expect(extractPriorReviewerNote([older, newer], 517)).toBe('newer reviewer note')
  })

  it('prefers the latest source=reviewer even when a later orchestrator one exists', () => {
    const reviewerFirst = buildEscalationComment({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'reviewer verdict text',
      runId: '100',
    })
    const orchestratorLater = buildEscalationComment({
      issueNumber: 517,
      reason: 'needs-human',
      source: 'orchestrator',
      note: 'budget exceeded',
      runId: '200',
    })
    expect(extractPriorReviewerNote([reviewerFirst, orchestratorLater], 517)).toBe('reviewer verdict text')
  })

  it('ignores escalations keyed to a different issue number', () => {
    // `issue=5178` must not satisfy a search for issue=517 (word-boundary).
    const otherIssue = buildEscalationComment({
      issueNumber: 5178,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'note on another cut',
    })
    expect(extractPriorReviewerNote([otherIssue], 517)).toBeNull()
  })

  it('ignores non-escalation outcome tags (needs-input, dep-waiting, etc.)', () => {
    const body = `Some bot comment carrying a different tag.

<!-- feature-bot: needs-input issue=517 run=1 source=reviewer -->`
    expect(extractPriorReviewerNote([body], 517)).toBeNull()
  })

  it('is defensive about null/undefined comment bodies', () => {
    // octokit types comment.body as optional; a deleted-then-restored
    // comment can surface as null.
    const body = buildEscalationComment({
      issueNumber: 517,
      reason: 'wrong-root-cause',
      source: 'reviewer',
      note: 'the note',
    })
    expect(extractPriorReviewerNote([null, undefined, body], 517)).toBe('the note')
  })

  it('preserves multi-line reviewer notes', () => {
    // escalateToHuman now prefixes each line with `> ` so the parser can
    // simply consume consecutive blockquote lines.
    const body = buildEscalationComment({
      issueNumber: 517,
      reason: 'refinement-exhausted',
      source: 'reviewer',
      note: 'line one\nline two\nline three',
    })
    expect(extractPriorReviewerNote([body], 517)).toBe('line one\nline two\nline three')
  })

  it('returns null when the note section is missing from a tagged comment', () => {
    // Defensive — a malformed comment should not mislead Agent A.
    const body = `Someone posted this manually.

<!-- feature-bot: escalation issue=517 reason=wrong-root-cause run=1 source=reviewer -->`
    expect(extractPriorReviewerNote([body], 517)).toBeNull()
  })
})

describe('escalation outcome-tag format in production code', () => {
  it("index.ts' escalateToHuman delegates to escalationOutcomeTag for the comment marker", () => {
    // The composition is shared with the parser so there's one spelling.
    expect(INDEX_SRC).toContain('escalationOutcomeTag(')
    // And the tag is interpolated into the comment body.
    expect(INDEX_SRC).toMatch(/\$\{tag\}/)
  })

  it('escalateToHuman carries a source parameter in its signature', () => {
    // The signature now takes `source: 'reviewer' | 'orchestrator'` so
    // every caller must classify what produced the note.
    expect(INDEX_SRC).toMatch(/source:\s*['"]reviewer['"]\s*\|\s*['"]orchestrator['"]/)
  })

  it("escalateToHuman's note formatting prefixes each line with `> `", () => {
    // Multi-line reviewer notes need per-line `> ` prefixes to render
    // (and parse) as one blockquote. Matches composeRefinementComment.
    expect(INDEX_SRC).toMatch(/reasonNote[^`]{0,100}\.replace\(\/\\n\/g,\s*['"]\\n>\s/)
  })
})

describe('index.ts seeds priorReviewerNote from historical reviewer-sourced escalations', () => {
  it('calls extractPriorReviewerNote before the generator-critic loop', () => {
    expect(INDEX_SRC).toContain('extractPriorReviewerNote')
  })

  it('imports extractPriorReviewerNote from the shared helper module', () => {
    expect(INDEX_SRC).toMatch(/from ['"]\.\/prior-reviewer-note(?:\.js)?['"]/)
  })
})

describe('route-attempt wiring', () => {
  it('escalate-needs-human decisions carry a source field', () => {
    // Discriminates reviewer-sourced notes (Agent B verdict) from
    // orchestrator-sourced notes (Agent A failure, cycle exhaustion).
    expect(ROUTE_ATTEMPT_SRC).toMatch(/source:\s*['"]reviewer['"]/)
    expect(ROUTE_ATTEMPT_SRC).toMatch(/source:\s*['"]orchestrator['"]/)
  })

  it('type declaration includes source on escalate-needs-human', () => {
    // Grep: the RouteDecision union's escalate-needs-human variant must
    // carry `source` so downstream consumers can emit the right outcome
    // tag. Without this, index.ts' escalateToHuman call site at
    // decision.kind === 'escalate-needs-human' cannot thread source.
    // Find the TYPE declaration (not the earlier JSDoc mention), then
    // slice to the next union-arm start to scope the match.
    const typeDeclIdx = ROUTE_ATTEMPT_SRC.indexOf("| { kind: 'escalate-needs-human'")
    expect(typeDeclIdx).toBeGreaterThan(-1)
    // The slice ends at the next union-arm start, bounding the match to
    // the escalate-needs-human variant alone.
    const nextArmIdx = ROUTE_ATTEMPT_SRC.indexOf('| { kind:', typeDeclIdx + 1)
    const slice = ROUTE_ATTEMPT_SRC.slice(typeDeclIdx, nextArmIdx === -1 ? undefined : nextArmIdx)
    expect(slice).toMatch(/source:\s*['"]reviewer['"]\s*\|\s*['"]orchestrator['"]/)
  })
})

describe('prompts/per-cut.md documents the requeue case', () => {
  it('PRIOR_REVIEWER_NOTE docs cover requeue after a reviewer escalation', () => {
    // Previously documented as "present only when ATTEMPT > 1"; a
    // requeued cut starts at ATTEMPT=1 but still receives the note.
    const idx = PROMPT_SRC.indexOf('PRIOR_REVIEWER_NOTE')
    expect(idx).toBeGreaterThan(-1)
    // Look within the vicinity of the PRIOR_REVIEWER_NOTE bullet.
    const section = PROMPT_SRC.slice(idx, idx + 600)
    expect(section).toMatch(/requeue|re-queue/i)
  })
})
