/**
 * Refinement hand-off tests — failing-test commit per rule 31 TDD-first.
 *
 * Covers the two pure pieces of the feature-bot → cut-planner channel
 * (design-cut-planner.md Q4):
 *
 *   - countPriorRefinements: the outcome tag is the durable budget record
 *   - composeRefinementComment: Agent B's note must survive verbatim
 *
 * The I/O half (createComment + label swap) lives in the orchestrator and
 * is covered by the wiring assertions at the bottom of this file.
 */
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { composeRefinementComment, countPriorRefinements, refinementMarker } from '../refinement-handoff.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const INDEX_SRC = readFileSync(resolve(HERE, '..', 'index.ts'), 'utf-8')

describe('countPriorRefinements', () => {
  it('returns 0 when no comment carries the marker', () => {
    expect(countPriorRefinements(['unrelated', 'also unrelated'], 519)).toBe(0)
  })

  it('counts only comments carrying THIS issue’s marker', () => {
    const bodies = [
      `handoff <!-- ${refinementMarker(519)} run=1 -->`,
      `handoff <!-- ${refinementMarker(520)} run=2 -->`, // different cut
      `handoff <!-- ${refinementMarker(519)} run=3 -->`,
    ]
    expect(countPriorRefinements(bodies, 519)).toBe(2)
  })

  it('is defensive about null/undefined comment bodies', () => {
    // octokit types comment.body as optional; a deleted-then-restored
    // comment can surface as null.
    expect(countPriorRefinements([null, undefined, `x <!-- ${refinementMarker(519)} -->`], 519)).toBe(1)
  })

  it('does not count a needs-input tag as a refinement', () => {
    // The two budgets are independent (MAX_INPUT_CYCLES vs maxRefinements);
    // sharing a marker prefix must not conflate them.
    expect(countPriorRefinements(['<!-- feature-bot: needs-input issue=519 run=1 -->'], 519)).toBe(0)
  })
})

describe('composeRefinementComment', () => {
  const base = {
    issueNumber: 519,
    reviewerNote: 'Architecture gap at manifest-save.ts:329-333 — the EDIT_LOCKED return path breaks the contract.',
    priorRefinements: 0,
    maxRefinements: 2,
    attempts: 2,
    runId: '37190295733',
  }

  it('quotes Agent B’s note verbatim', () => {
    // Q6: "a refinement that doesn't quote Agent B's note is just a retry".
    const body = composeRefinementComment(base)
    expect(body).toContain('manifest-save.ts:329-333')
    expect(body).toContain('EDIT_LOCKED return path breaks the contract')
  })

  it('states which refinement this is, so the budget is visible', () => {
    expect(composeRefinementComment(base)).toContain('refinement 1 of 2')
    expect(composeRefinementComment({ ...base, priorRefinements: 1 })).toContain('refinement 2 of 2')
  })

  it('carries the outcome tag so the next run can count it', () => {
    const body = composeRefinementComment(base)
    expect(body).toContain(refinementMarker(519))
    expect(body).toContain('run=37190295733')
    // Round-trip: the comment it produces must be countable by the counter.
    expect(countPriorRefinements([body], 519)).toBe(1)
  })

  it('says explicitly that the cut is NOT abandoned', () => {
    // The whole point of the non-terminal tier. A maintainer reading the
    // comment must not mistake it for a terminal escalation.
    const body = composeRefinementComment(base)
    expect(body).toMatch(/not abandoned|No skip-list entry/i)
  })

  it('carries the AI-authorship disclaimer', () => {
    // Project convention: every AI-authored comment is labelled as such.
    expect(composeRefinementComment(base)).toMatch(/generated by AI/i)
  })

  it('survives a multi-line reviewer note without breaking the blockquote', () => {
    const body = composeRefinementComment({ ...base, reviewerNote: 'line one\nline two' })
    expect(body).toContain('> line one')
    expect(body).toContain('> line two')
  })
})

describe('orchestrator wiring', () => {
  it('handles the escalate-needs-refinement decision', () => {
    expect(INDEX_SRC).toContain("decision.kind === 'escalate-needs-refinement'")
  })

  it('swaps ready-for-agent → needs-refinement on hand-off', () => {
    expect(INDEX_SRC).toContain('needs-refinement')
    expect(INDEX_SRC).toMatch(/removeLabel\([^)]*'ready-for-agent'/s)
  })

  it('does NOT write a skip-list entry on the refinement path', () => {
    // The non-terminal guarantee: escalateToHuman appends a skip entry and
    // opens a PR for it, so the refinement branch must not call it.
    //
    // Slice to the branch's OWN closing brace rather than a fixed character
    // window — a fixed window overshoots into the `loop-exhausted` fallback
    // below, which legitimately calls escalateToHuman, and would fail for
    // the wrong reason.
    const start = INDEX_SRC.indexOf("decision.kind === 'escalate-needs-refinement'")
    expect(start).toBeGreaterThan(-1)
    const breakIdx = INDEX_SRC.indexOf('break', start)
    const branch = INDEX_SRC.slice(start, breakIdx)
    expect(branch).toContain('handOffForRefinement')
    expect(branch).not.toContain('escalateToHuman')
  })

  it('passes a refinement budget into RouteContext', () => {
    expect(INDEX_SRC).toMatch(/maxRefinements:/)
    expect(INDEX_SRC).toMatch(/priorRefinements:/)
  })
})
