/**
 * Comment bodies cut-planner posts. Pure text; every body ends with an
 * outcome tag (bots/README.md convention) and opens with the AI-authorship
 * disclaimer every bot comment carries.
 *
 * Plain language per rule 23: each comment says what happened, why, and what
 * a human needs to do — nothing more. Decision comments on the planner issue
 * use the `> Decision:` form so the comment log reads as the feature's
 * reasoning history (Q7).
 */
import {
  decisionMarker,
  escalatedCutMarker,
  escalatedFeatureMarker,
  redecomposedMarker,
  refinedMarker,
  tag,
} from './markers.js'

const AI = '> *This was generated by AI during a cut-planner run.*'

/** Planner-issue log entry for a filed cut. */
export function filedComment(o: {
  feature: string
  cutNumber: number
  title: string
  deviation: string | null
  queued: boolean
  runId: string
}): string {
  const dev = o.deviation ? `\n\n> Decision: deviated from the suggested plan — ${o.deviation}` : ''
  const q = o.queued
    ? 'Queued for feature-bot (`ready-for-agent`).'
    : 'Recorded but **not queued**: it edits `.github/workflows/**`, which `GITHUB_TOKEN` cannot push (#840). Needs a manual PR.'
  return `${AI}

> Decision: filed #${o.cutNumber} — ${o.title}. ${q}${dev}

${tag(decisionMarker(o.feature, 'filed'), o.runId)}`
}

/** On a freshly filed cut that is recorded but not queued (#840). */
export function workflowCutComment(runId: string, cutNumber: number): string {
  return `${AI}

This cut edits files under \`.github/workflows/\`. The bots push with \`GITHUB_TOKEN\`, which cannot modify workflow files under any permission (#840), so feature-bot would build and review it and then be unable to deliver it.

It is filed as \`ready-for-human\` instead of \`ready-for-agent\`: please implement it with a manual PR. This stops being necessary once the bots move to a GitHub App token (#336).

${tag(escalatedCutMarker(cutNumber), runId)}`
}

/** On a cut whose spec cut-planner revised. */
export function refinedCutComment(o: { cutNumber: number; summary: string; queued: boolean; runId: string }): string {
  const q = o.queued
    ? 'Swapped `needs-refinement` → `ready-for-agent`; feature-bot will pick this up on its next run.'
    : 'The revised spec edits `.github/workflows/**`, so it is moved to `ready-for-human` instead (#840).'
  return `${AI}

**Spec revised** in response to the reviewer's verdict above.

${o.summary.trim()}

${q}

${tag(refinedMarker(o.cutNumber), o.runId)}`
}

/** Planner-issue log entry for a refinement. */
export function refinedLogComment(o: { feature: string; cutNumber: number; summary: string; runId: string }): string {
  return `${AI}

> Decision: refined #${o.cutNumber} — ${o.summary.trim()}

${tag(decisionMarker(o.feature, 'refined'), o.runId)}`
}

/** On the original cut, closed by a re-decomposition. */
export function supersededComment(o: { replacement: number; runId: string; cutNumber: number }): string {
  return `${AI}

Closing: refinement did not land this cut, so it has been split. The first replacement is #${o.replacement}; the remaining pieces are recorded on the planner issue and will be filed one at a time.

${tag(escalatedCutMarker(o.cutNumber), o.runId)}`
}

/** Planner-issue log entry for a re-decomposition — this tag IS the per-feature budget counter. */
export function redecomposedComment(o: {
  feature: string
  original: number
  replacement: number
  remaining: readonly string[]
  summary: string
  runId: string
}): string {
  const rest = o.remaining.map(r => `- ${r}`).join('\n')
  return `${AI}

> Decision: re-decomposed #${o.original} — ${o.summary.trim()}

Filed #${o.replacement} first. Still to file, one at a time:

${rest}

${tag(redecomposedMarker(o.feature), o.runId)}`
}

/** Terminal escalation of one cut (Q6a, cut scope). The rest of the feature continues. */
export function escalateCutComment(o: { cutNumber: number; reason: string; detail: string; runId: string }): string {
  return `${AI}

**Needs a human.** cut-planner can't take this cut any further (\`${o.reason}\`).

${o.detail.trim()}

I've moved it to \`ready-for-human\`, so neither bot will pick it up again. The rest of the feature keeps going: this only blocks this cut.

${tag(escalatedCutMarker(o.cutNumber), o.runId)}`
}

/** Feature-scope escalation on the planner issue (Q6a). Stops filing for the feature. */
export function escalateFeatureComment(o: { feature: string; reason: string; detail: string; runId: string }): string {
  return `${AI}

**Needs a human.** cut-planner has stopped filing cuts for **${o.feature}** (\`${o.reason}\`).

${o.detail.trim()}

I've added \`needs-info\`. Remove it once this is resolved and I'll pick the feature up again on the next run.

${tag(escalatedFeatureMarker(o.feature), o.runId)}`
}

/** A design question cut-planner may not answer itself (Q2). Same shape as feature-bot's NEEDS_INPUT. */
export function questionComment(o: {
  feature: string
  question: string
  options: readonly string[]
  recommendation: string
  runId: string
}): string {
  const opts = o.options.map(x => `- ${x}`).join('\n')
  return `${AI}

**A design decision is needed before the next cut can be specified.** The planner issue doesn't lock this, and cut-planner transcribes locked decisions rather than making them.

**Question:** ${o.question.trim()}

**Options:**

${opts}

**Recommendation:** ${o.recommendation.trim()}

Once decided, add the answer to \`## Locked decisions\` above and remove \`needs-info\`.

${tag(escalatedFeatureMarker(o.feature), o.runId)}`
}
