/**
 * Comment-body builder tests.
 *
 * Pin the invariants cut-planner's comment convention relies on:
 *
 *   (1) **AI disclaimer**: every bot comment opens with the AI-authorship
 *       disclaimer so maintainers reading an issue thread can tell bot
 *       output from human notes (`bots/README.md` disclaimer convention,
 *       `team-preferences.md` rule 38 symmetric-bots discipline). A silent
 *       drop would make bot output indistinguishable from human comments.
 *
 *   (2) **Outcome tag**: every body ends with a `<!-- marker run=X -->`
 *       trailer whose `marker` is produced by the matching `markers.ts`
 *       helper — that's how `countMarked()` finds a comment on a later
 *       run (`markers.ts` module docstring: "the same string has to be
 *       used to WRITE a tag and to COUNT it"). A manually-renamed marker
 *       would silently reset the Q6 budgets to zero.
 *
 *   (3) **Pipeline-mechanic phrasing** (`ready-for-agent` /
 *       `needs-refinement` / `ready-for-human` / `needs-info`): these are
 *       the operator-facing label-state transitions. A branch-flip that
 *       swapped them would misreport the queue state to the maintainer.
 *
 *   (4) **Krug-aligned plain-language** (`team-preferences.md` rule 23)
 *       for escalations: "Needs a human" phrasing + option bullets rather
 *       than internal-jargon.
 *
 * These are not covered by `execute.test.ts`, which asserts on comment
 * delivery (did the bot post the right comment on the right issue?) with
 * a single incidental content substring. The content contract lives here.
 */
import { describe, expect, it } from 'vitest'
import {
  escalateCutComment,
  escalateFeatureComment,
  filedComment,
  questionComment,
  redecomposedComment,
  refinedCutComment,
  refinedLogComment,
  supersededComment,
  workflowCutComment,
} from '../comments.js'
import {
  decisionMarker,
  escalatedCutMarker,
  escalatedFeatureMarker,
  redecomposedMarker,
  refinedMarker,
  tag,
} from '../markers.js'

const AI_DISCLAIMER = '> *This was generated by AI during a cut-planner run.*'
const RUN = 'run-99'

/** Every builder's output, keyed by name, for cross-cutting invariants. */
const everyBody = (): ReadonlyArray<readonly [string, string]> => [
  [
    'filedComment',
    filedComment({
      feature: 'review-workflow',
      cutNumber: 11,
      title: 'wire the gate',
      deviation: null,
      queued: true,
      runId: RUN,
    }),
  ],
  ['workflowCutComment', workflowCutComment(RUN, 11)],
  ['refinedCutComment', refinedCutComment({ cutNumber: 11, summary: 'tightened spec', queued: true, runId: RUN })],
  [
    'refinedLogComment',
    refinedLogComment({ feature: 'review-workflow', cutNumber: 11, summary: 'tightened spec', runId: RUN }),
  ],
  ['supersededComment', supersededComment({ cutNumber: 11, replacement: 42, runId: RUN })],
  [
    'redecomposedComment',
    redecomposedComment({
      feature: 'review-workflow',
      original: 11,
      replacement: 42,
      remaining: ['the other piece'],
      summary: 'split in two',
      runId: RUN,
    }),
  ],
  [
    'escalateCutComment',
    escalateCutComment({ cutNumber: 11, reason: 'refinement-exhausted', detail: 'tried twice', runId: RUN }),
  ],
  [
    'escalateFeatureComment',
    escalateFeatureComment({
      feature: 'review-workflow',
      reason: 'open-question',
      detail: 'need maintainer input',
      runId: RUN,
    }),
  ],
  [
    'questionComment',
    questionComment({
      feature: 'review-workflow',
      question: 'What hash?',
      options: ['A', 'B'],
      recommendation: 'A',
      runId: RUN,
    }),
  ],
]

describe('every builder — cross-cutting invariants', () => {
  // Counterfactual: dropping the `AI` constant line in comments.ts makes
  // bot output indistinguishable from a human comment on the issue thread,
  // defeating the bots/README.md disclaimer convention.
  it.each(everyBody())('%s opens with the AI-authorship disclaimer', (_name, body) => {
    expect(body.startsWith(AI_DISCLAIMER)).toBe(true)
  })

  // Counterfactual: trailing whitespace or a stray newline below the tag
  // doesn't break counting, but a missing `<!-- ... -->` wrapper around
  // the marker would — the convention is HTML-comment-wrapped markers only.
  it.each(everyBody())('%s ends with a trailing HTML-comment outcome tag', (_name, body) => {
    expect(body.trimEnd()).toMatch(/<!-- cut-planner: [^>]+ run=run-99 -->$/)
  })
})

describe('filedComment', () => {
  const base = {
    feature: 'review-workflow',
    cutNumber: 11,
    title: 'wire the gate',
    runId: RUN,
  }

  it('names the cut it filed (number + title) so a reader does not need to click through', () => {
    // Counterfactual: emitting "filed a cut" without the number/title
    // means every planner-issue log entry looks the same; readers can't
    // scan the history without opening each referenced issue.
    const body = filedComment({ ...base, deviation: null, queued: true })
    expect(body).toContain('#11')
    expect(body).toContain('wire the gate')
  })

  it('reports queued state when the cut is handed to feature-bot', () => {
    // Counterfactual: a branch-flip to the not-queued path would promise
    // a `ready-for-human` escalation that never happened, misleading
    // the operator about which label the cut actually carries.
    const body = filedComment({ ...base, deviation: null, queued: true })
    expect(body).toContain('ready-for-agent')
    expect(body).not.toContain('#840')
  })

  it('reports workflow-restricted state when the cut is recorded but not queued', () => {
    // Counterfactual: a branch-flip to the queued path would advertise
    // auto-pickup for a cut `GITHUB_TOKEN` cannot land (#840); operator
    // waits forever for a build that will not run.
    const body = filedComment({ ...base, deviation: null, queued: false })
    expect(body).toContain('.github/workflows/**')
    expect(body).toContain('#840')
    expect(body).toContain('not queued')
  })

  it('omits the deviation line entirely when no deviation was recorded', () => {
    // Counterfactual: emitting the "deviated from the suggested plan"
    // sentence unconditionally would make every single filed cut read
    // as a deviation, destroying Q3's audit-of-deviations invariant.
    const body = filedComment({ ...base, deviation: null, queued: true })
    expect(body).not.toContain('deviated from the suggested plan')
  })

  it('records the deviation reasoning as a `> Decision:` line when present', () => {
    // Counterfactual: dropping the deviation text would satisfy Q3's
    // "deviation must be recorded" rule in spirit only — the audit trail
    // would say "a deviation happened" without saying what or why.
    const body = filedComment({
      ...base,
      deviation: 'folded cut 6 into 5 — same files, revertability intact',
      queued: true,
    })
    expect(body).toContain(
      '> Decision: deviated from the suggested plan — folded cut 6 into 5 — same files, revertability intact',
    )
  })

  it('ends with the planner-issue decision tag so counting finds filings per feature', () => {
    // Counterfactual: swapping to a cut-scoped marker (e.g.
    // `escalatedCutMarker(cutNumber)`) would make `countMarked` miss
    // this filing when summing per-feature state on the planner issue.
    const body = filedComment({ ...base, deviation: null, queued: true })
    expect(body).toContain(tag(decisionMarker('review-workflow', 'filed'), RUN))
  })
})

describe('workflowCutComment', () => {
  it('cites both the workflow-token restriction (#840) and the long-term fix (#336)', () => {
    // Counterfactual: dropping either citation leaves the operator with
    // the symptom but no tracking context — "why is this manual?" and
    // "when does it stop being manual?" are the two questions readers ask.
    const body = workflowCutComment(RUN, 11)
    expect(body).toContain('#840')
    expect(body).toContain('#336')
  })

  it('tells the operator the cut was filed as ready-for-human, not ready-for-agent', () => {
    // Counterfactual: no mention of the actual label applied would force
    // the operator to open the issue to find out what state it is in.
    const body = workflowCutComment(RUN, 11)
    expect(body).toContain('ready-for-human')
  })

  it('uses the cut-scoped escalation marker (one cut parked, feature still proceeds)', () => {
    // Counterfactual: using the feature-scoped marker would stop
    // cut-planner filing further cuts for the whole feature; this is a
    // single-cut parking, not a feature-level block.
    expect(workflowCutComment(RUN, 11)).toContain(tag(escalatedCutMarker(11), RUN))
  })
})

describe('refinedCutComment', () => {
  const summary = 'tightened the spec — now names manifest-save.ts explicitly'

  it('includes the revised spec body (trimmed) so Agent A can act on it next run', () => {
    // Counterfactual: dropping the summary would leave Agent A to reverse-
    // engineer what changed from the label swap alone.
    const body = refinedCutComment({ cutNumber: 11, summary: `   ${summary}   `, queued: true, runId: RUN })
    expect(body).toContain(summary)
  })

  it('reports the needs-refinement → ready-for-agent swap when the revised cut is queued', () => {
    // Counterfactual: a branch-flip would advertise a `ready-for-human`
    // label on a cut that is actually about to re-enter feature-bot's
    // queue — the operator sees the wrong next step.
    const body = refinedCutComment({ cutNumber: 11, summary, queued: true, runId: RUN })
    expect(body).toContain('needs-refinement')
    expect(body).toContain('ready-for-agent')
    expect(body).not.toContain('ready-for-human')
  })

  it('reports the needs-refinement → ready-for-human path when the revised cut edits workflows', () => {
    // Counterfactual: a branch-flip would promise auto-pickup for a
    // revised cut that `GITHUB_TOKEN` still cannot deliver (#840).
    const body = refinedCutComment({ cutNumber: 11, summary, queued: false, runId: RUN })
    expect(body).toContain('ready-for-human')
    expect(body).toContain('#840')
  })

  it('carries the cut-scoped refined marker so the Q6 budget counter sees it', () => {
    // Counterfactual: renaming the marker string by hand (e.g. s/refined/
    // revised/) would make `countMarked(bodies, refinedMarker(N))` return
    // zero — the Q6 refinement budget (2 attempts max) would silently
    // reset on every run.
    const body = refinedCutComment({ cutNumber: 11, summary, queued: true, runId: RUN })
    expect(body).toContain(tag(refinedMarker(11), RUN))
  })
})

describe('refinedLogComment', () => {
  const summary = 'reused manifest-save.ts invalidation path per #837'

  it('uses the `> Decision:` form so the planner-issue log reads as reasoning history', () => {
    // Counterfactual: dropping `> Decision:` makes the planner-issue
    // comment stream unparseable as a feature's decision history
    // (design-cut-planner.md Q7: "comments answer how did we get here").
    const body = refinedLogComment({ feature: 'review-workflow', cutNumber: 11, summary, runId: RUN })
    expect(body).toContain(`> Decision: refined #11 — ${summary}`)
  })

  it('uses the feature-scoped marker (log entry on the planner issue), not the cut-scoped one', () => {
    // Counterfactual: swapping to `refinedMarker(cutNumber)` (cut-scoped)
    // would make per-feature state queries on the planner issue miss this
    // event — the two markers address different scopes deliberately.
    const body = refinedLogComment({ feature: 'review-workflow', cutNumber: 11, summary, runId: RUN })
    expect(body).toContain(tag(decisionMarker('review-workflow', 'refined'), RUN))
  })

  it('trims whitespace from the summary so caller formatting does not leak into the log', () => {
    // Counterfactual: no trim would preserve leading/trailing whitespace
    // from the caller's input; the planner-issue log would show
    // "> Decision: refined #11 —     <text>  " on every refinement.
    const body = refinedLogComment({
      feature: 'review-workflow',
      cutNumber: 11,
      summary: `\n\n  ${summary}  \n`,
      runId: RUN,
    })
    expect(body).toContain(`> Decision: refined #11 — ${summary}`)
    expect(body).not.toContain(`  ${summary}`)
  })
})

describe('supersededComment', () => {
  it('points the reader at the replacement cut so the trail is followable', () => {
    // Counterfactual: dropping the replacement number means the reader
    // sees "closed by re-decomposition" with no next-link.
    const body = supersededComment({ cutNumber: 11, replacement: 42, runId: RUN })
    expect(body).toContain('#42')
  })

  it('frames the closure as a split, not a plain close', () => {
    // Counterfactual: a mutation emitting "closed as not planned" would
    // misclassify a re-decomposition as abandonment in the audit trail.
    const body = supersededComment({ cutNumber: 11, replacement: 42, runId: RUN })
    expect(body).toMatch(/split/i)
  })

  it('tags the ORIGINAL cut (not the replacement), scoped at cut level', () => {
    // Counterfactual: tagging the replacement number would make
    // forensic "when was #11 superseded?" queries find nothing.
    const body = supersededComment({ cutNumber: 11, replacement: 42, runId: RUN })
    expect(body).toContain(tag(escalatedCutMarker(11), RUN))
  })
})

describe('redecomposedComment', () => {
  const base = {
    feature: 'review-workflow',
    original: 11,
    replacement: 42,
    summary: 'split into two: route + handler',
    runId: RUN,
  }

  it('opens with a `> Decision: re-decomposed #<original>` planner-issue log line', () => {
    // Counterfactual: dropping the `> Decision:` marker leaves the
    // planner-issue log without the discriminator Q7 relies on.
    const body = redecomposedComment({ ...base, remaining: ['the handler piece'] })
    expect(body).toContain(`> Decision: re-decomposed #11 — ${base.summary}`)
  })

  it('renders each remaining piece on its own bulleted line (not concatenated)', () => {
    // Counterfactual: joining the remaining pieces with spaces instead of
    // newlines would make the planner-issue "still to file" section a
    // single run-on sentence, defeating rule 23's scannability contract.
    const body = redecomposedComment({
      ...base,
      remaining: ['piece A — route', 'piece B — handler'],
    })
    expect(body).toContain('- piece A — route')
    expect(body).toContain('- piece B — handler')
    // Each bullet is on its own line.
    expect(body).toMatch(/- piece A — route\n- piece B — handler/)
  })

  it('names the replacement cut as the first one filed', () => {
    // Counterfactual: dropping "first" relationship means the reader
    // cannot tell which of the N listed pieces was actually filed.
    const body = redecomposedComment({ ...base, remaining: ['the handler piece'] })
    expect(body).toContain('#42')
  })

  it('uses the feature-scoped redecomposed marker (Q6 budget: 1 re-decomposition max)', () => {
    // Counterfactual: using an issue-scoped marker (e.g.
    // `escalatedCutMarker`) would make the per-feature budget counter
    // miss the event, allowing unbounded re-decomposition.
    const body = redecomposedComment({ ...base, remaining: ['the handler piece'] })
    expect(body).toContain(tag(redecomposedMarker('review-workflow'), RUN))
  })
})

describe('escalateCutComment', () => {
  const base = {
    cutNumber: 11,
    reason: 'refinement-exhausted',
    detail: 'two refinement rounds landed no verdict; the spec is not the problem.',
    runId: RUN,
  }

  it('opens with plain-language "Needs a human" rather than internal jargon', () => {
    // Counterfactual: a Krug-violating phrasing like "ESCALATED:
    // refinement-exhausted" would read as internal telemetry; the
    // audience here is the maintainer, not a dashboard.
    const body = escalateCutComment(base)
    expect(body).toContain('**Needs a human.**')
  })

  it('renders the reason as inline code so it is grep-friendly and discriminable from prose', () => {
    // Counterfactual: emitting the reason as bare prose makes a scan
    // over past escalations ("find every refinement-exhausted") a
    // substring hunt instead of a lexical match.
    const body = escalateCutComment(base)
    expect(body).toContain('`refinement-exhausted`')
  })

  it('includes the detail block so the operator does not need to replay the transcript', () => {
    // Counterfactual: dropping `detail` leaves the operator with
    // "needs human, idk why" and forces a transcript download.
    const body = escalateCutComment(base)
    expect(body).toContain(base.detail)
  })

  it('names the ready-for-human label the cut now carries', () => {
    // Counterfactual: without `ready-for-human` the operator cannot
    // verify in GitHub whether the label was actually applied.
    const body = escalateCutComment(base)
    expect(body).toContain('ready-for-human')
  })

  it('uses the cut-scoped escalated marker; the rest of the feature keeps going', () => {
    // Counterfactual: a feature-scoped marker here would halt filing
    // for the whole feature on one cut's local failure — exactly
    // what Q6a's narrower-scope lock warns against.
    expect(escalateCutComment(base)).toContain(tag(escalatedCutMarker(11), RUN))
  })
})

describe('escalateFeatureComment', () => {
  const base = {
    feature: 'review-workflow',
    reason: 'open-question',
    detail: 'needs a lock on the hash basis for invalidateOnSave.',
    runId: RUN,
  }

  it('opens with plain-language "Needs a human" like the cut-scope escalation does', () => {
    // Counterfactual: inconsistent phrasing between cut-scope and
    // feature-scope escalations defeats maintainer pattern recognition.
    const body = escalateFeatureComment(base)
    expect(body).toContain('**Needs a human.**')
  })

  it('bolds the feature name so the scope is unmistakable at a glance', () => {
    // Counterfactual: unbolded feature name blends with the sentence;
    // scanning "which feature is stuck?" across N planner issues gets
    // slower, which matters because feature-scope escalations are rarer
    // and worth higher visual weight.
    const body = escalateFeatureComment(base)
    expect(body).toContain('**review-workflow**')
  })

  it('renders the reason in backticks (same convention as the cut-scope path)', () => {
    const body = escalateFeatureComment(base)
    expect(body).toContain('`open-question`')
  })

  it('names needs-info — the feature-level label, not ready-for-human', () => {
    // Counterfactual: the two label mechanics are the Q6a scope split;
    // `ready-for-human` applied to a planner issue would re-queue
    // feature-bot inappropriately once the label was removed.
    const body = escalateFeatureComment(base)
    expect(body).toContain('needs-info')
    expect(body).not.toContain('ready-for-human')
  })

  it('uses the feature-scoped escalated marker so filing stops for the whole feature', () => {
    // Counterfactual: cut-scoped marker here would allow cut-planner
    // to keep filing cuts for a feature with an unresolved
    // feature-level block.
    expect(escalateFeatureComment(base)).toContain(tag(escalatedFeatureMarker('review-workflow'), RUN))
  })
})

describe('questionComment', () => {
  const base = {
    feature: 'review-workflow',
    question: 'Should invalidateOnSave hash the manifest or the publish state?',
    options: ['Hash computeSaveEtag(manifest)', 'Hash the publish-state .{8hex}.hash'],
    recommendation: 'Hash computeSaveEtag(manifest) — per #837.',
    runId: RUN,
  }

  it('labels the question / options / recommendation sections distinctly', () => {
    // Counterfactual: dropping any of the three section labels forces
    // the maintainer to parse structure from prose; the three-part
    // shape mirrors feature-bot's NEEDS_INPUT contract and is what
    // makes the comment answerable in one scan.
    const body = questionComment(base)
    expect(body).toContain('**Question:**')
    expect(body).toContain('**Options:**')
    expect(body).toContain('**Recommendation:**')
  })

  it('renders each option on its own bulleted line (not concatenated)', () => {
    // Counterfactual: emitting options as "A, B" or space-joined would
    // defeat the compare-side-by-side reading pattern operators use
    // on these questions.
    const body = questionComment(base)
    expect(body).toContain('- Hash computeSaveEtag(manifest)')
    expect(body).toContain('- Hash the publish-state .{8hex}.hash')
    expect(body).toMatch(/- Hash computeSaveEtag\(manifest\)\n- Hash the publish-state/)
  })

  it('trims whitespace from the question and the recommendation', () => {
    // Counterfactual: no trim means an LLM-authored prompt with trailing
    // newlines produces "**Question:** ...\n\n" with ragged spacing.
    const body = questionComment({
      ...base,
      question: `  ${base.question}  \n`,
      recommendation: `\n${base.recommendation}  `,
    })
    expect(body).toContain(`**Question:** ${base.question}`)
    expect(body).toContain(`**Recommendation:** ${base.recommendation}`)
  })

  it('tells the maintainer where to record the answer and how to unblock', () => {
    // Counterfactual: without `## Locked decisions` + `needs-info`, the
    // maintainer answers in a reply comment that cut-planner cannot
    // read — the question stays "answered" from a human POV but open
    // from the bot's POV, and the feature stalls indefinitely.
    const body = questionComment(base)
    expect(body).toContain('## Locked decisions')
    expect(body).toContain('needs-info')
  })

  it('tags at feature scope so the feature stays paused until the answer lands', () => {
    // Counterfactual: cut-scope tag would let cut-planner file the next
    // cut for this feature while a design question is unresolved —
    // Q6a's "feature can't proceed → feature scope" invariant.
    expect(questionComment(base)).toContain(tag(escalatedFeatureMarker('review-workflow'), RUN))
  })
})
