/**
 * Comment-renderer tests.
 *
 * Two invariants matter, per the module docstrings in `comments.ts` and
 * `markers.ts`:
 *
 * - Every renderer opens with the AI-authorship disclaimer (the triage-skill
 *   convention cited in `comments.ts:3-10`). Without it a maintainer scanning
 *   an issue thread can't tell bot output from human notes.
 * - Every renderer closes with the correct outcome tag for its marker. Per
 *   `markers.ts`'s module docstring: every budget in design-cut-planner.md Q6
 *   is counted from tagged comments, and the SAME string has to WRITE a tag
 *   that COUNT reads. A renderer that drops the tag or picks the wrong marker
 *   silently resets a budget to zero, with no compiler signal.
 *
 * Delegating to the real `tag()` / `*Marker()` from `markers.ts` for every
 * expected value means writer + reader cannot drift: if markers.ts renames
 * a marker, both sides follow in the same commit.
 */
import { describe, expect, it } from 'vitest'
import {
  escalateCutComment,
  escalateFeatureComment,
  filedComment,
  questionComment,
  redecomposedComment,
  refinedCutComment,
  refinedLogComment,
  supersededComment,
  workflowCutComment,
} from '../comments.js'
import {
  decisionMarker,
  escalatedCutMarker,
  escalatedFeatureMarker,
  redecomposedMarker,
  refinedMarker,
  tag,
} from '../markers.js'

const AI_DISCLAIMER = '> *This was generated by AI during a cut-planner run.*'
const RUN_ID = 'r1'

/**
 * One row per exported comment function. Each row names the renderer, a
 * thunk that calls it with representative inputs, and the exact tag the
 * output must end with — expressed as a composition of `tag()` and the
 * renderer-specific `*Marker()`.
 */
const CASES: readonly { name: string; render: () => string; expectedTag: string }[] = [
  {
    name: 'filedComment',
    render: () =>
      filedComment({
        feature: 'review-workflow',
        cutNumber: 42,
        title: 'gate saves',
        deviation: null,
        queued: true,
        runId: RUN_ID,
      }),
    // Decision log on the planner issue: feature-scope filed-marker.
    expectedTag: tag(decisionMarker('review-workflow', 'filed'), RUN_ID),
  },
  {
    name: 'workflowCutComment',
    render: () => workflowCutComment(RUN_ID, 42),
    expectedTag: tag(escalatedCutMarker(42), RUN_ID),
  },
  {
    name: 'refinedCutComment',
    render: () =>
      refinedCutComment({
        cutNumber: 42,
        summary: 'summary',
        queued: true,
        runId: RUN_ID,
      }),
    // Per-cut refinement budget: `issue-index.ts:88` reads `refinedMarker(issue)`.
    expectedTag: tag(refinedMarker(42), RUN_ID),
  },
  {
    name: 'refinedLogComment',
    render: () =>
      refinedLogComment({
        feature: 'review-workflow',
        cutNumber: 42,
        summary: 'summary',
        runId: RUN_ID,
      }),
    expectedTag: tag(decisionMarker('review-workflow', 'refined'), RUN_ID),
  },
  {
    name: 'supersededComment',
    render: () =>
      supersededComment({
        replacement: 100,
        runId: RUN_ID,
        cutNumber: 42,
      }),
    expectedTag: tag(escalatedCutMarker(42), RUN_ID),
  },
  {
    name: 'redecomposedComment',
    render: () =>
      redecomposedComment({
        feature: 'review-workflow',
        original: 42,
        replacement: 100,
        remaining: ['piece A', 'piece B'],
        summary: 'split into three',
        runId: RUN_ID,
      }),
    // Per-feature re-decomposition budget: `index.ts:226` reads `redecomposedMarker(feature)`.
    expectedTag: tag(redecomposedMarker('review-workflow'), RUN_ID),
  },
  {
    name: 'escalateCutComment',
    render: () =>
      escalateCutComment({
        cutNumber: 42,
        reason: 'refinement-exhausted',
        detail: 'detail',
        runId: RUN_ID,
      }),
    expectedTag: tag(escalatedCutMarker(42), RUN_ID),
  },
  {
    name: 'escalateFeatureComment',
    render: () =>
      escalateFeatureComment({
        feature: 'review-workflow',
        reason: 'open-decision',
        detail: 'detail',
        runId: RUN_ID,
      }),
    expectedTag: tag(escalatedFeatureMarker('review-workflow'), RUN_ID),
  },
  {
    name: 'questionComment',
    render: () =>
      questionComment({
        feature: 'review-workflow',
        question: 'q',
        options: ['a', 'b'],
        recommendation: 'a',
        runId: RUN_ID,
      }),
    expectedTag: tag(escalatedFeatureMarker('review-workflow'), RUN_ID),
  },
]

describe('comment renderers — AI-authorship disclaimer', () => {
  // Counterfactual: a refactor that moves the disclaimer below a header,
  // alters the convention text, or drops it altogether would fail this —
  // which is the whole point, since the disclaimer is the first visible
  // row of every bot comment and the only cue a scanning maintainer
  // sees before reading the body.
  it.each(CASES)('$name opens with the disclaimer', ({ render }) => {
    expect(render().startsWith(AI_DISCLAIMER)).toBe(true)
  })
})

describe('comment renderers — trailing outcome tag', () => {
  // Counterfactual: a refactor that swaps `decisionMarker` for
  // `escalatedCutMarker`, drops the tag block, or hardcodes the run id
  // would fail this. Each of those regressions silently breaks a budget
  // counter in `issue-index.ts` or `index.ts` without producing a type
  // error.
  it.each(CASES)('$name ends with its outcome tag', ({ render, expectedTag }) => {
    expect(render().endsWith(expectedTag)).toBe(true)
  })

  // Counterfactual: if `tag()` or a renderer stopped embedding the raw
  // marker string (e.g. switched to a JSON blob), `countMarked` would
  // return zero because it checks `body.includes(marker)` literally.
  it.each(CASES)('$name body includes the marker string `countMarked` scans for', ({ render, expectedTag }) => {
    expect(render()).toContain(expectedTag)
  })
})

describe('comment renderers — budget markers do not collapse into one another', () => {
  // The per-cut and per-feature budgets have distinct scopes. These
  // tests pin the specific swaps a refactor could silently make, each
  // of which would redirect a counter and reset a budget to zero.

  it('refinedCutComment uses `refinedMarker(cut)`, not the feature-scope decision marker', () => {
    // `issue-index.ts:88` counts refinements with `refinedMarker(cut)`.
    // Swapping to `decisionMarker(feature, 'refined')` (which looks
    // plausible — refinedLogComment uses it on the planner issue) would
    // leave the per-cut counter at zero forever.
    const body = refinedCutComment({ cutNumber: 42, summary: 's', queued: true, runId: RUN_ID })
    expect(body).toContain(tag(refinedMarker(42), RUN_ID))
    expect(body).not.toContain(tag(decisionMarker('review-workflow', 'refined'), RUN_ID))
  })

  it('redecomposedComment uses `redecomposedMarker(feature)`, not a cut-scope sibling', () => {
    // `index.ts:226` counts re-decompositions with per-feature
    // `redecomposedMarker(feature)`. A plausible-looking refactor might
    // reach for a cut-scope sibling (`escalatedCutMarker(original)` or
    // `refinedMarker(original)`), which would produce text the
    // feature-scope counter never matches — budget silently stuck at
    // zero. (Note: `decisionMarker(feature, 'redecomposed')` happens to
    // produce text-identical output to `redecomposedMarker(feature)`,
    // so it is NOT a meaningful mutation and is not asserted against.)
    const body = redecomposedComment({
      feature: 'review-workflow',
      original: 42,
      replacement: 100,
      remaining: [],
      summary: 's',
      runId: RUN_ID,
    })
    expect(body).toContain(tag(redecomposedMarker('review-workflow'), RUN_ID))
    expect(body).not.toContain(tag(escalatedCutMarker(42), RUN_ID))
    expect(body).not.toContain(tag(refinedMarker(42), RUN_ID))
  })

  it('escalateCutComment and escalateFeatureComment carry different-scope markers', () => {
    // Q6a: a cut-scope escalation blocks one cut; a feature-scope
    // escalation stops filing for the whole feature. Conflating the two
    // markers would merge the two scopes — a cut escalation would
    // register as a feature escalation and halt the entire feature.
    const cutBody = escalateCutComment({
      cutNumber: 42,
      reason: 'r',
      detail: 'd',
      runId: RUN_ID,
    })
    const featureBody = escalateFeatureComment({
      feature: 'review-workflow',
      reason: 'r',
      detail: 'd',
      runId: RUN_ID,
    })
    expect(cutBody).toContain(tag(escalatedCutMarker(42), RUN_ID))
    expect(cutBody).not.toContain(tag(escalatedFeatureMarker('review-workflow'), RUN_ID))
    expect(featureBody).toContain(tag(escalatedFeatureMarker('review-workflow'), RUN_ID))
    expect(featureBody).not.toContain(tag(escalatedCutMarker(42), RUN_ID))
  })
})
