import { describe, expect, it, vi } from 'vitest'
import { addLabel, hasPriorBotComment, hasPriorCommentFromBot } from '../github.js'

const REPO = { owner: 'gazetta-studio', repo: 'gazetta-studio' }

/** Shape an `issues.listComments` response from a list of body strings. */
function makeListComments(bodies: Array<string | null | undefined>) {
  return vi.fn().mockResolvedValue({ data: bodies.map(body => ({ body })) })
}

describe('hasPriorBotComment', () => {
  it('returns true when a comment starts with the AI triage disclaimer prefix', async () => {
    // Counterfactual: if the impl looked for any other marker (e.g. a Co-Authored-By
    // trailer or an outcome tag) the disclaimer-prefixed comment would no longer match.
    const listComments = makeListComments(['> *This was generated by AI during triage.*\n\nHere are my findings...'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(true)
  })

  it('returns false when no comment starts with the disclaimer prefix', async () => {
    // Counterfactual: if the impl returned true on ANY comment existing, this fails.
    const listComments = makeListComments([
      'I think this is a real bug, can you reproduce?',
      'Bumping this — still happening on main',
    ])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(false)
  })

  it('returns false when a maintainer comment mentions "triage" without the disclaimer prefix', async () => {
    // The exact ambiguity called out in the JSDoc: pre-computing this at the
    // orchestrator level (rather than Claude parsing) eliminates the false
    // positive where a maintainer's comment containing the word "triage" got
    // miscounted as prior bot output.
    // Counterfactual: if the impl used `body.includes('triage')` instead of the
    // anchored disclaimer prefix, the maintainer's comment below would match.
    const listComments = makeListComments(['Started looking at this during triage — looks like a race condition'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(false)
  })

  it('requires the disclaimer at the START of the body, not anywhere in it', async () => {
    // The JSDoc promises the prefix is detected "at the start of any comment
    // body." A disclaimer-shaped string quoted in the middle of a maintainer's
    // reply must not register as bot output.
    // Counterfactual: if the impl used .includes() instead of .startsWith(),
    // this quoted-reply body would falsely match.
    const listComments = makeListComments([
      'Thanks for the response! You said:\n\n> *This was generated by AI during triage.*\n\nOK got it.',
    ])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(false)
  })

  it('tolerates leading whitespace before the disclaimer prefix', async () => {
    // Bot output occasionally lands with a leading newline (e.g., Markdown-
    // renderers that emit a blank line before block quotes). The contract is
    // "starts with the disclaimer" semantically, not byte-exact.
    // Counterfactual: if the impl used raw .startsWith() without trimStart(),
    // a leading newline would defeat the check — and a future cron seeing the
    // SAME issue would re-add the first-investigation labels (the "this is my
    // first time here" branch). This test pins trimStart()'s necessity.
    const listComments = makeListComments(['\n\n> *This was generated by AI during triage.*\n\nMy findings...'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(true)
  })

  it('treats null/undefined body as absent rather than crashing', async () => {
    // Octokit's TS type allows `body?: string | null`. Defensive handling
    // matters: a single null-body comment in the middle of a list must not
    // throw — that would silently abort the bot's idempotency check and
    // force re-investigation on every cron.
    // Counterfactual: if the impl called .startsWith() on a null body without
    // the `?? ''` fallback, this would throw TypeError.
    const listComments = makeListComments([null, undefined, 'real comment'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(false)
  })

  it('returns false when the issue has no comments at all', async () => {
    // Zero-comments is the "brand-new issue" case triage-bot's idempotency
    // check hits on every first investigation. If the impl iterated through
    // `data` assuming non-empty (e.g., threw on `.some()` misuse or returned
    // truthy for an empty array), the "first time here" branch would never
    // fire and every cron would skip fresh issues.
    // Counterfactual: if the impl returned true (or threw) on the zero-comments
    // case, this would fail.
    const listComments = makeListComments([])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorBotComment(octokit, REPO, 123)).toBe(false)
  })
})

describe('hasPriorCommentFromBot', () => {
  it("returns true when a comment contains the named bot's outcome tag", async () => {
    // Counterfactual: if the impl looked for the wrong tag shape (e.g.,
    // `<!-- bot: discovery-prep-bot` instead of `<!-- discovery-prep-bot: run=`)
    // the realistic outcome tag below would no longer match.
    const listComments = makeListComments(['Research notes:\n\n<!-- discovery-prep-bot: run=12345 -->'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorCommentFromBot(octokit, REPO, 123, 'discovery-prep-bot')).toBe(true)
  })

  it('matches the tag even when it appears at the end of a longer comment body', async () => {
    // Real bot comments land the outcome tag at the very end (after prose
    // summary, next steps, disclosure block). A prefix-only match would miss
    // every actual bot comment — the contract is `.includes()`, not
    // `.startsWith()`.
    // Counterfactual: if the impl used .startsWith(tag) instead of
    // .includes(tag), this end-of-body tag would not match.
    const preFetched = [
      { body: 'Long prose summary of what triage-bot did.\n\nNext steps: ...\n\n<!-- triage-bot: run=99 -->' },
    ]
    expect(await hasPriorCommentFromBot({} as never, REPO, 123, 'triage-bot', preFetched)).toBe(true)
  })

  it("returns false when no comment contains the named bot's tag", async () => {
    // Counterfactual: if the impl returned true whenever ANY outcome tag was
    // present (regardless of bot name), this would falsely return true.
    const listComments = makeListComments(['<!-- triage-bot: run=12345 -->', '<!-- flake-watcher: run=67890 -->'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorCommentFromBot(octokit, REPO, 123, 'discovery-prep-bot')).toBe(false)
  })

  it("discriminates bot names exactly — fix-bot's tag does not match feature-bot", async () => {
    // The whole point of chain-dispatch is bot-specific. Loose matching
    // (substring on bot name) would mean a fix-bot tag triggered the
    // "feature-bot has commented" branch and skipped a legitimate dispatch.
    // Counterfactual: if the impl used .includes(botName) without the `<!-- `
    // and `: run=` anchors, "bot" would match any bot tag.
    const listComments = makeListComments(['<!-- fix-bot: run=12345 -->'])
    const octokit = { issues: { listComments } } as never
    expect(await hasPriorCommentFromBot(octokit, REPO, 123, 'feature-bot')).toBe(false)
  })

  it('skips the API call when comments are pre-supplied via the optional parameter', async () => {
    // The JSDoc promises: "Caller can pre-fetch the comments and reuse via the
    // comments parameter to avoid duplicate API calls when checking multiple
    // bots' tags on the same issue."
    // Counterfactual: if the impl ignored the `comments` parameter and always
    // fetched from the API, listComments would have been called and this
    // assertion would fail.
    const listComments = vi.fn()
    const octokit = { issues: { listComments } } as never
    const preFetched = [{ body: '<!-- discovery-prep-bot: run=99 -->' }]
    const result = await hasPriorCommentFromBot(octokit, REPO, 123, 'discovery-prep-bot', preFetched)
    expect(result).toBe(true)
    expect(listComments).not.toHaveBeenCalled()
  })

  it('fetches from the API when no comments parameter is supplied', async () => {
    // The complementary half of the pre-fetch optimisation: without the
    // parameter, the helper must still work on its own by querying the API.
    // Counterfactual: if the impl always required the parameter (or always
    // skipped the call), this would either crash or return false despite
    // a matching tag living in the API response.
    const listComments = makeListComments(['<!-- discovery-prep-bot: run=42 -->'])
    const octokit = { issues: { listComments } } as never
    const result = await hasPriorCommentFromBot(octokit, REPO, 123, 'discovery-prep-bot')
    expect(result).toBe(true)
    expect(listComments).toHaveBeenCalledTimes(1)
    expect(listComments.mock.calls[0]?.[0]).toMatchObject({
      ...REPO,
      issue_number: 123,
    })
  })

  it('tolerates null/undefined body in pre-supplied comments', async () => {
    // Same defensive contract as hasPriorBotComment. Octokit's response shape
    // and any caller-supplied subset both permit nullable body.
    // Counterfactual: if the impl called .includes() on a null body without
    // the `?? ''` fallback, this would throw TypeError.
    const listComments = vi.fn()
    const octokit = { issues: { listComments } } as never
    const preFetched = [{ body: null }, { body: undefined }, { body: '<!-- feature-bot: run=1 -->' }]
    expect(await hasPriorCommentFromBot(octokit, REPO, 123, 'feature-bot', preFetched)).toBe(true)
  })
})

describe('addLabel', () => {
  it('forwards owner/repo/issue_number and the label-as-singleton-array to issues.addLabels', async () => {
    // Counterfactual: if the impl called a different endpoint (e.g.,
    // `update` with a labels mutation, or `setLabels` which REPLACES labels),
    // either the mock would not be called or the request payload shape would
    // differ — both fail the assertion below.
    const addLabels = vi.fn().mockResolvedValue({})
    const octokit = { issues: { addLabels } } as never
    await addLabel(octokit, REPO, 123, 'ready-for-human')
    expect(addLabels).toHaveBeenCalledTimes(1)
    expect(addLabels.mock.calls[0]?.[0]).toEqual({
      ...REPO,
      issue_number: 123,
      labels: ['ready-for-human'],
    })
  })

  it('resolves without a return value on success', async () => {
    // The JSDoc declares `Promise<void>`. Callers must not depend on a return
    // value (no `if (added) { ... }` branches in bot orchestrators).
    // Counterfactual: if the impl returned the addLabels response (a
    // non-undefined Octokit shape), callers could grow brittle branches; this
    // assertion catches the contract drift.
    const addLabels = vi.fn().mockResolvedValue({ data: [{ name: 'whatever' }] })
    const octokit = { issues: { addLabels } } as never
    const result = await addLabel(octokit, REPO, 123, 'ready-for-human')
    expect(result).toBeUndefined()
  })
})
