import { describe, expect, it, vi } from 'vitest'
import { hasPriorBotComment, hasPriorCommentFromBot } from '../github.js'

const REPO = { owner: 'gazetta-studio', repo: 'gazetta-studio' }

function makeOctokit(comments: Array<{ body?: string | null }>) {
  return {
    issues: {
      listComments: vi.fn().mockResolvedValue({ data: comments }),
    },
  } as never
}

describe('hasPriorBotComment', () => {
  // Counterfactual: would fail if the impl forgot the prefix check (e.g. returned false unconditionally).
  it('returns true when a comment body starts with the AI triage disclaimer prefix', async () => {
    const octokit = makeOctokit([{ body: '> *This was generated by AI during triage.*\n\nReproduces on macOS 15.' }])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(true)
  })

  // Counterfactual: would fail if the impl used `startsWith` without `trimStart` — the documented behaviour
  // is the prefix lookup happens after leading-whitespace normalisation so renderers / editors that add a
  // leading newline don't break detection.
  it('returns true when the disclaimer is preceded by leading whitespace', async () => {
    const octokit = makeOctokit([{ body: '\n  > *This was generated by AI during triage.*\n\nfollow-on text' }])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(true)
  })

  // Counterfactual: would fail if the impl returned true unconditionally.
  it('returns false when no comments carry the disclaimer prefix', async () => {
    const octokit = makeOctokit([
      { body: 'Looks like a flake to me.' },
      { body: 'I am triaging this now.' },
      { body: 'Cannot reproduce locally.' },
    ])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(false)
  })

  // Counterfactual: would fail if the impl used `includes` instead of `startsWith`. This is the documented
  // disambiguation case — a maintainer's free-text comment that happens to mention "triage" must NOT count
  // as prior bot activity; the JSDoc calls this out as the bug the helper exists to prevent.
  it('returns false when the disclaimer-shaped text appears mid-body, not at start', async () => {
    const octokit = makeOctokit([
      { body: 'Some intro text. > *This was generated by AI during triage.* — that quote came from another issue.' },
    ])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(false)
  })

  // Counterfactual: would fail if the impl iterated through `data` assuming non-empty and threw / returned
  // truthy on the zero-comments case.
  it('returns false when the issue has no comments at all', async () => {
    const octokit = makeOctokit([])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(false)
  })

  // Counterfactual: would fail if the impl dereferenced `c.body` without the `?? ''` fallback. Ghost users
  // and deleted comments can present a null body in Octokit responses; the helper must tolerate them.
  it('tolerates comments with null body', async () => {
    const octokit = makeOctokit([{ body: null }, { body: '> *This was generated by AI during triage.*\n\nbot output' }])
    const result = await hasPriorBotComment(octokit, REPO, 288)
    expect(result).toBe(true)
  })
})

describe('hasPriorCommentFromBot', () => {
  // Counterfactual: would fail if the impl never built / looked for the outcome-tag prefix.
  it("returns true when a comment contains the bot's outcome tag", async () => {
    const octokit = makeOctokit([{ body: 'Some prose.\n\n<!-- discovery-prep-bot: run=12345 -->' }])
    const result = await hasPriorCommentFromBot(octokit, REPO, 288, 'discovery-prep-bot')
    expect(result).toBe(true)
  })

  // Counterfactual: would fail if the impl returned true unconditionally.
  it('returns false when no comments contain the tag', async () => {
    const octokit = makeOctokit([
      { body: 'unrelated comment' },
      { body: '<!-- fix-bot: run=999 -->' }, // a different bot's tag must NOT match
    ])
    const result = await hasPriorCommentFromBot(octokit, REPO, 288, 'discovery-prep-bot')
    expect(result).toBe(false)
  })

  // Counterfactual: would fail if the impl always called `listComments` regardless of the `comments`
  // argument. The pre-fetched path is the documented optimisation — it lets triage-bot check multiple
  // downstream bots' tags against ONE comment fetch instead of N round-trips per issue.
  it('uses the pre-fetched comments parameter and skips the API call', async () => {
    const listComments = vi.fn()
    const octokit = { issues: { listComments } } as never
    const preFetched = [{ body: '<!-- discovery-prep-bot: run=42 -->' }]

    const result = await hasPriorCommentFromBot(octokit, REPO, 288, 'discovery-prep-bot', preFetched)

    expect(result).toBe(true)
    expect(listComments).not.toHaveBeenCalled()
  })

  // Counterfactual: would fail if the impl returned false (or threw) when the optional parameter was
  // omitted. The default path must fall back to the API call.
  it('calls the API when the comments parameter is not provided', async () => {
    const listComments = vi.fn().mockResolvedValue({
      data: [{ body: '<!-- fix-bot: run=7 -->' }],
    })
    const octokit = { issues: { listComments } } as never

    const result = await hasPriorCommentFromBot(octokit, REPO, 288, 'fix-bot')

    expect(result).toBe(true)
    expect(listComments).toHaveBeenCalledTimes(1)
    expect(listComments.mock.calls[0]?.[0]).toMatchObject({ issue_number: 288, per_page: 100 })
  })

  // Counterfactual: would fail if the impl had a generic "any outcome tag" check rather than interpolating
  // botName. The JSDoc calls this out as the contract — chain-dispatch decisions depend on per-bot
  // specificity (triage-bot wants to know whether discovery-prep-bot already commented, NOT whether
  // ANY bot commented).
  it('distinguishes between different bot names', async () => {
    const comments = [{ body: '<!-- discovery-prep-bot: run=1 -->' }]

    const truthy = await hasPriorCommentFromBot({} as never, REPO, 288, 'discovery-prep-bot', comments)
    const falsy = await hasPriorCommentFromBot({} as never, REPO, 288, 'fix-bot', comments)

    expect(truthy).toBe(true)
    expect(falsy).toBe(false)
  })

  // Counterfactual: would fail if the impl used `startsWith` instead of `includes`. Outcome tags land at
  // the end of bot comments (after the prose body), so prefix matching would miss every real bot comment.
  it('matches the tag even when it appears at the end of the comment body', async () => {
    const comments = [
      {
        body: 'Long prose summary of what triage-bot did.\n\nNext steps: ...\n\n<!-- triage-bot: run=99 -->',
      },
    ]
    const result = await hasPriorCommentFromBot({} as never, REPO, 288, 'triage-bot', comments)
    expect(result).toBe(true)
  })

  // Counterfactual: would fail if the impl dereferenced `c.body` without the `?? ''` fallback.
  it('tolerates pre-fetched comments with null body', async () => {
    const comments = [{ body: null }, { body: '<!-- fix-bot: run=1 -->' }]
    const result = await hasPriorCommentFromBot({} as never, REPO, 288, 'fix-bot', comments)
    expect(result).toBe(true)
  })
})
