/**
 * Refinement hand-off — the feature-bot → cut-planner channel.
 *
 * Per design-cut-planner.md Q4, feature-bot hands a cut to cut-planner by
 * doing exactly two things on the CUT issue:
 *
 *   1. posting an outcome-tagged comment carrying Agent B's verdict
 *   2. swapping `ready-for-agent` → `needs-refinement`
 *
 * That is the whole protocol. feature-bot never learns the planner issue
 * exists, never resolves its number, and cannot fail because of it — the
 * label IS the channel. An earlier draft had feature-bot cross-post a
 * summary to the planner issue; that was rejected because it introduces a
 * new way for feature-bot to break on a path that must not break.
 *
 * The dequeue is free: the candidate query prefilters server-side on label
 * PRESENCE (`labels: requireAll.join(',')` in bots/_lib/github.ts), so
 * removing `ready-for-agent` removes the cut from feature-bot's queue with
 * no parser change and no new exclusion.
 *
 * This module holds the pure pieces — comment body composition and prior-
 * refinement counting — so they are testable without octokit. The I/O
 * (createComment, addLabel, removeLabel) stays in the orchestrator per the
 * same split that puts routing in route-attempt.ts (rule 18: I/O and
 * decision logic are different reasons-to-change).
 */

/** Outcome tag marker for a refinement hand-off on a given cut issue. */
export function refinementMarker(issueNumber: number): string {
  return `feature-bot: needs-refinement issue=${issueNumber}`
}

/**
 * Count prior refinement hand-offs for this cut from its comment bodies.
 *
 * Mirrors `countPriorInputCycles`: the outcome tag is the durable record,
 * so the count survives runner restarts, cache misses, and re-runs without
 * any committed state. Per design-cut-planner.md Q6 this feeds
 * `RouteContext.priorHandoffs`.
 */
export function countPriorRefinements(
  commentBodies: readonly (string | null | undefined)[],
  issueNumber: number,
): number {
  const marker = refinementMarker(issueNumber)
  return commentBodies.filter(b => (b ?? '').includes(marker)).length
}

export interface RefinementCommentInput {
  issueNumber: number
  /** Agent B's verbatim rejection note. */
  reviewerNote: string
  /** How many refinements this cut has already had (0 on the first). */
  priorHandoffs: number
  /** Budget from RouteContext.maxHandoffs. */
  maxHandoffs: number
  /** Attempts the generator-critic loop spent before giving up. */
  attempts: number
  /** GitHub Actions run id, or 'local'. */
  runId: string
}

/**
 * Compose the hand-off comment.
 *
 * Carries Agent B's note VERBATIM — per design-cut-planner.md Q6, "a
 * refinement that doesn't quote Agent B's note is just a retry". Truncated
 * only at a generous ceiling so a long architectural critique survives
 * intact; GitHub's comment limit is 65536 chars.
 */
export function composeRefinementComment(input: RefinementCommentInput): string {
  const attemptOf = `${input.priorHandoffs + 1} of ${input.maxHandoffs}`
  return `> *This was generated by AI during a feature-bot run.*

**Handed to cut-planner** — hand-off ${attemptOf}.

The generator-critic loop spent ${input.attempts} attempt(s) and Agent B rejected each one on substance, so the spec may be the cause rather than the implementation. Handing this to cut-planner rather than giving up.

**Agent B's last verdict:**

> ${input.reviewerNote.slice(0, 4000).replace(/\n/g, '\n> ')}

I've swapped \`ready-for-agent\` → \`needs-refinement\`, so I will not pick this cut up again until cut-planner revises the spec and swaps the label back. No skip-list entry was written: this cut is not abandoned.

<!-- ${refinementMarker(input.issueNumber)} run=${input.runId} -->`
}

/**
 * Was this cut filed by cut-planner?
 *
 * Only such cuts may be handed off. cut-planner reads `needs-refinement`
 * only for features that have a planner issue, so handing off an old-model
 * cut (filed before cut-planner existed — review-workflow's, say) would park
 * it in a queue no bot reads: the silent parking design-cut-planner.md Q6a
 * forbids. Those cuts keep the pre-cut-planner behaviour and escalate to a
 * human when the loop exhausts.
 *
 * Read from the cut's own body (cut-planner's outcome tag), so feature-bot
 * still never learns the planner issue exists (Q4). The string is
 * duplicated from cut-planner's `filedCutMarker` because the bots share no
 * code; a contract test in cut-planner pins the two copies together.
 */
export function filedByCutPlanner(issueBody: string): boolean {
  return issueBody.includes('<!-- cut-planner: filed feature=')
}
